# Generated by Django 5.0.6 on 2024-07-01 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(max_length=50, unique=True)),
                ('discount_price', models.IntegerField(default=150)),
                ('mininum_amount', models.IntegerField(default=750)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('quantity', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
