# Generated by Django 5.0.6 on 2024-07-01 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='mininum_amount',
            new_name='minimum_amount',
        ),
    ]
