# Generated by Django 5.0.6 on 2024-07-18 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_orderitem_return_request_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='return_request_time',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='return_status',
        ),
    ]
