# Generated by Django 5.0.6 on 2024-06-09 04:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usermodels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=800)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.BigIntegerField(validators=[django.core.validators.MaxValueValidator(limit_value=1000000000, message='Phone number must have at least 10 digits.'), django.core.validators.MaxValueValidator(limit_value=9999999999, message='Phone number must have at most 10 digits.')])),
                ('password1', models.IntegerField()),
                ('password2', models.IntegerField()),
            ],
        ),
    ]
