# Generated by Django 5.0.6 on 2024-06-10 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodels',
            name='is_block',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usermodels',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usermodels',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
