# Generated by Django 5.0.6 on 2024-06-10 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_usermodels_is_block_usermodels_is_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodels',
            name='otp',
        ),
    ]
