# Generated by Django 5.0.6 on 2024-06-13 11:00

import django.core.validators
from django.db import migrations, models
import django.utils.timezone

def set_default_join_date(apps, schema_editor):
    Usermodels = apps.get_model('authentication', 'Usermodels')  # Replace 'your_app_name' with your actual app name
    Usermodels.objects.filter(join_date=None).update(join_date=django.utils.timezone.now())


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_usermodels_is_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodels',
            name='join_date',
            field=models.DateTimeField(default=None, blank=True, null=True),
            preserve_default=False
        ),
        migrations.RunPython(set_default_join_date),
        migrations.AddField(
            model_name='usermodels',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
        migrations.AlterField(
            model_name='usermodels',
            name='password1',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='usermodels',
            name='password2',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='usermodels',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinValueValidator(1000000000, message='Phone number must be at least 10 digits.'), django.core.validators.MaxValueValidator(9999999999, message='Phone number must be at most 10 digits.')]),
        ),
    ]
