# Generated by Django 5.0.6 on 2024-06-20 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_usermodels_join_date_usermodels_profile_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodels',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='usermodels',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
