# Generated by Django 5.0.6 on 2024-07-11 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_usermodels_email_alter_usermodels_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodels',
            name='profile_photo',
            field=models.ImageField(default='media/profile_photos/gender-neutral-user.jpg', upload_to='profile_photos/'),
        ),
    ]
