# Generated by Django 5.0.6 on 2024-07-16 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_usermodels_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodels',
            name='profile_photo',
            field=models.ImageField(default='/profile_photos/gender-neutral-user.jpg', upload_to='profile_photos/'),
        ),
    ]
