# Generated by Django 5.0.6 on 2024-07-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_usermodels_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodels',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
