# Generated by Django 5.0.6 on 2024-06-28 07:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0006_alter_usermodels_email_alter_usermodels_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(10, message='Phone number must be at least 10 digits.')])),
                ('address_line', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=150)),
                ('postal_code', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.usermodels')),
            ],
        ),
    ]
