# Generated by Django 5.0.6 on 2024-06-30 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='address_line',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='email',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='postal_code',
        ),
        migrations.AddField(
            model_name='useraddress',
            name='apartment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='fullname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
