# Generated by Django 5.0.6 on 2024-06-30 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_remove_useraddress_address_line_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
