# Generated by Django 5.0.6 on 2024-07-04 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_useraddress_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
