# Generated by Django 5.0.6 on 2024-06-14 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(max_length=255, unique=True)),
                ('is_listed', models.BooleanField(default=True)),
            ],
        ),
    ]
