# Generated by Django 5.0.6 on 2024-06-20 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_image_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='product_image',
            new_name='Variant_image',
        ),
        migrations.RenameField(
            model_name='variant_image',
            old_name='product',
            new_name='variant',
        ),
    ]
