# Generated by Django 5.0.6 on 2024-06-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_variant_is_available_variant_image_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
